version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sahar
      MYSQL_DATABASE: khaddemApp
    ports:
      - "3306:3306"
    volumes:
      - khaddemApp:/var/lib/mysql

  app-kaddem:
    depends_on:
      - mysqldb
    image: sahargaiche11/khadem:latest
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON:
        '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/khaddemApp?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "sahar",
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    stdin_open: true
    tty: true

volumes:
  khaddemApp: