pipeline {
    agent any

    stages {
        stage('Install dependencies') {
            steps {
                dir('kaddem') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('kaddem') {
                    sh 'mvn test'
                }
            }
        }
          stage('SonarQube Analysis') {
                steps {
                    dir('kaddem') {  
                        withSonarQubeEnv('sonnar_devops') {
                            sh 'sonar-scanner_devops'
                        }
                    }
                }
        stage('Build application') {
            steps {
                dir('kaddem') {
                    sh 'mvn package'
                }
            }
        }

        }
    }
}
