pipeline {
    agent any

    stages {
        stage('Install dependencies') {
            steps {
                dir('.') {  // Exécute les commandes dans le répertoire courant (kaddem)
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('.') {  // Exécute les commandes dans le répertoire courant (kaddem)
                    sh 'mvn test'
                }
            }
        }
        stage('Build application') {
            steps {
                dir('.') {  // Exécute les commandes dans le répertoire courant (kaddem)
                    sh 'mvn package'
                }
            }
        }
    }
}